#ifndef FILETYPESHANDLER_H
#define FILETYPESHANDLER_H

#define HTMLFILETYPE 0
#define CSSFILETYPE 1
#define JSFILETYPE 2
#define SCSSFILETYPE 3
#define TYPESCRIPTFILETYPE 4

#endif // !FILETYPESHANDLER_H